name: Create Release & Upload To Maven

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup
        id: setup
        run: |
          echo "TAG VERSION: ${{ github.ref_name }}"
          echo "RELEASE NAME: ${GITHUB_REF#refs/tags/v}"
          echo "::set-output name=release_name::${GITHUB_REF#refs/tags/v}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ steps.setup.outputs.release_name }}
          draft: false
          prerelease: false
      - name: Setup GPG Key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | gpg --dearmor > secret_key.gpg
          ls
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          echo "" >> gradle.properties
          echo "mavenCentralUsername=${{ secrets.OSSRH_USERNAME }}" >> gradle.properties
          echo "" >> gradle.properties
          echo "mavenCentralPassword=${{ secrets.OSSRH_PASSWORD }}" >> gradle.properties
          echo "" >> gradle.properties
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties
          echo "" >> gradle.properties >> gradle.properties
          echo "signing.password=${{ secrets.SIGNING_KEY_PASSWORD }}" >> gradle.properties
          echo "" >> gradle.properties >> gradle.properties
          echo "signing.secretKeyRingFile=../secret_key.gpg" >> gradle.properties
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
      - name: Gradlew Tasks
        run: |
          ./gradlew clean
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          echo "---------------------------||---------------------------"
          chmod +x update_version.sh
          ./update_version.sh kotlin_feature_network/build.gradle.kts 0.0.1-beta ${{ steps.setup.outputs.release_name }}
          ./gradlew :kotlin_feature_network:publishMavenPublicationToMavenCentralRepository
          
