name: Create Tag Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v3
      - name: Gradlew Tasks
        run: |
          ./gradlew tasks --all
          
