name: Create Tag Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Gradlew Tasks
        run: |
          ls
          ./gradlew tasks --all
          
