name: Create Tag Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup GPG Key
        run: |
          echo ${{ secrets.SECRING_GPG_BASE64 }} | base64 -d > secring.gpg
          ls
          echo "" >> gradle.properties
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties
          echo "" >> gradle.properties >> gradle.properties
          echo "signing.password=${{ secrets.SIGNING_KEY_PASSWORD }}" >> gradle.properties
          echo "" >> gradle.properties >> gradle.properties
          echo "signing.secretKeyRingFile=../secring.gpg" >> gradle.properties
          cat gradle.properties
      - name: Gradlew Tasks
        run: |
          ./gradlew tasks --all
          ./gradlew :kotlin_feature_network:publishMavenPublicationToMavenCentralRepository
          
